version: '3.1'
services:
  mosquitto:
      image: eclipse-mosquitto
      hostname: mosquitto
      container_name: mosquitto
      ports:
        - "8883:8883"
      volumes: 
        - ./mosquitto:/mosquitto/config
      networks:
        - webnet

networks:
  webnet: